# Generated by Django 6.0.5 on 2026-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_note_image_remove_note_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='password',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='notemedia',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
