# Generated by Django 6.0.5 on 2026-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_note_password_remove_note_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notemedia',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('file', 'File')], default='image', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notemedia',
            name='file',
            field=models.FileField(upload_to='note_media/'),
        ),
    ]
